# Generated by Django 5.2.4 on 2025-07-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_tag_photo_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("encoding", models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name="photo",
            name="persons",
            field=models.ManyToManyField(blank=True, to="gallery.person"),
        ),
    ]
